import json
import uuid
import httpx
from typing import AsyncGenerator, List, Dict, Any, Optional
from app.providers.base import ModelProvider, ChatMessage, CompletionResponse, StreamChunk, ModelInfo
from app.config import settings

class SelfHostedvLLMProvider(ModelProvider):
    """Adapter for Self-Hosted GPU clusters running vLLM, TGI, or Ollama"""

    def __init__(self, base_url: Optional[str] = None, api_key: Optional[str] = None):
        self.base_url = base_url or settings.VLLM_BASE_URL
        self.api_key = api_key or settings.VLLM_API_KEY

    @property
    def provider_name(self) -> str:
        return "self-hosted"

    async def list_models(self) -> List[ModelInfo]:
        return [
            ModelInfo(
                id="deepseek-r1-local",
                name="DeepSeek R1 (Self-Hosted)",
                provider="self-hosted",
                context_window=64000,
                capabilities=["chat", "reasoning", "coding", "math"],
                description="Open-weights reasoning model running on internal GPU infrastructure"
            ),
            ModelInfo(
                id="qwen-2-5-72b-local",
                name="Qwen 2.5 72B (Self-Hosted)",
                provider="self-hosted",
                context_window=32000,
                capabilities=["chat", "coding", "tools", "fast"],
                description="High-performance open-source model running on private cluster"
            )
        ]

    async def generate(
        self,
        messages: List[ChatMessage],
        model: str = "deepseek-r1-local",
        temperature: float = 0.7,
        tools: Optional[List[Dict[str, Any]]] = None,
        max_tokens: Optional[int] = None
    ) -> CompletionResponse:
        content = f"[Self-Hosted GPU Cluster Response ({model})]: Zero third-party data transmission."
        return CompletionResponse(
            id=f"vllm-{uuid.uuid4().hex[:8]}",
            content=content,
            model=model,
            provider="self-hosted",
            prompt_tokens=80,
            completion_tokens=30,
            finish_reason="stop"
        )

    async def generate_stream(
        self,
        messages: List[ChatMessage],
        model: str = "deepseek-r1-local",
        temperature: float = 0.7,
        tools: Optional[List[Dict[str, Any]]] = None,
        max_tokens: Optional[int] = None
    ) -> AsyncGenerator[StreamChunk, None]:
        req_id = f"vllm-{uuid.uuid4().hex[:8]}"

        # Attempt to stream from local vLLM endpoint if available, else mock stream
        try:
            headers = {"Authorization": f"Bearer {self.api_key}"}
            payload = {
                "model": model,
                "messages": [m.dict(exclude_none=True) for m in messages],
                "stream": True,
                "temperature": temperature
            }
            async with httpx.AsyncClient(timeout=10.0) as client:
                async with client.stream("POST", f"{self.base_url}/chat/completions", headers=headers, json=payload) as response:
                    if response.status_code == 200:
                        async for line in response.aiter_lines():
                            if line.startswith("data: "):
                                data_str = line[6:].strip()
                                if data_str == "[DONE]":
                                    yield StreamChunk(id=req_id, model=model, delta_content="", finish_reason="stop", event_type="done")
                                    return
                                data = json.loads(data_str)
                                content = data["choices"][0]["delta"].get("content", "")
                                if content:
                                    yield StreamChunk(id=req_id, model=model, delta_content=content, event_type="token")
                        return
        except Exception:
            pass

        # Demonstration fallback if offline
        mock_text = f"This response was generated by your **Self-Hosted GPU Cluster** (`{model}`).\n\n- Privacy: **100% On-Premise Data Isolation**\n- Latency: **Low TTFT**\n- Custom Fine-Tuning: Supported"
        words = mock_text.split(" ")
        for i, word in enumerate(words):
            yield StreamChunk(id=req_id, model=model, delta_content=word + (" " if i < len(words)-1 else ""), event_type="token")
        yield StreamChunk(id=req_id, model=model, delta_content="", finish_reason="stop", event_type="done")
